wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: huggingface
    huggingface_version: 4.6.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      4: 3.7.7
      5: 0.10.30
      6: 4.6.1
      8:
      - 5
asset_dir:
  desc: null
  value: asset/
batch_size:
  desc: null
  value: 64
clip_grad:
  desc: null
  value: 10
config:
  desc: null
  value: bert
config_path:
  desc: null
  value: ./config/config.yml
data_dir:
  desc: null
  value: /opt/ml/input/data/train_dataset
device:
  desc: null
  value: cuda
drop_out:
  desc: null
  value: 0.2
file_name:
  desc: null
  value: train_data.csv
hidden_dim:
  desc: null
  value: 64
log_steps:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.0001
max_seq_len:
  desc: null
  value: 20
model:
  desc: null
  value: Bert
model_dir:
  desc: null
  value: models/
model_name:
  desc: null
  value: bert.pt
n_epochs:
  desc: null
  value: 20
n_heads:
  desc: null
  value: 2
n_layers:
  desc: null
  value: 2
n_questions:
  desc: null
  value: 9455
n_tag:
  desc: null
  value: 913
n_test:
  desc: null
  value: 1538
name:
  desc: null
  value: bert
num_workers:
  desc: null
  value: 1
optimizer:
  desc: null
  value: adam
output_dir:
  desc: null
  value: output/
patience:
  desc: null
  value: 5
scheduler:
  desc: null
  value: plateau
seed:
  desc: null
  value: 42
test_file_name:
  desc: null
  value: test_data.csv
