lstm:
  seed: 42
  device: 'cpu'
  data_dir: '/opt/ml/input/data/train_dataset'
  asset_dir: 'asset/'
  file_name: 'tuning_train_data.csv'
  model_dir: 'models/' # model directory
  model_name: 'lstm.pt' # save model as model_name
  output_dir: 'output/'
  test_file_name: 'tuning_test_data.csv'  
  max_seq_len: 20
  num_workers: 1
  model_args:
    model: 'LSTM' # model class name
    hidden_dim: 512
    n_layers: 2
    n_heads: 2
    drop_out: 0.2
  train_args:
    n_epochs: 30
    batch_size: 64
    lr: 0.001
    clip_grad: 10
    patience: 20
    log_steps: 50
    optimizer: 'adamW'
    scheduler: 'plateau'
  wandb:
    name: 'lstm' # wandb run name

lstmattn:
  seed: 42
  device: 'cpu'
  data_dir: '/opt/ml/input/data/train_dataset'
  asset_dir: 'asset/'
  file_name: 'tuning_train_data.csv'
  model_dir: 'models/' # model directory
  model_name: 'lstmattn.pt' # save model as model_name
  output_dir: 'output/'
  test_file_name: 'tuning_test_data.csv'  
  max_seq_len: 20
  num_workers: 1
  model_args:
    model: 'LSTMATTN' # model class name
    hidden_dim: 512
    n_layers: 2
    n_heads: 2
    drop_out: 0.2
  train_args:
    n_epochs: 30
    batch_size: 64
    lr: 0.001
    clip_grad: 10
    patience: 20
    log_steps: 50
    optimizer: 'adamW'
    scheduler: 'plateau'
  wandb:
    name: 'lstmattn' # wandb run name

bert:
  seed: 42
  device: 'cpu'
  data_dir: '/opt/ml/input/data/train_dataset'
  asset_dir: 'asset/'
  file_name: 'tuning_train_data_2.csv'
  model_dir: 'models/' # model directory
  model_name: 'bert.pt' # save model as model_name
  output_dir: 'output/'
  test_file_name: 'tuning_test_data.csv'  
  max_seq_len: 20
  num_workers: 1
  model_args:
    model: 'Bert' # model class name
    hidden_dim: 64
    n_layers: 2
    n_heads: 2
    drop_out: 0.2
  train_args:
    n_epochs: 20
    batch_size: 64
    lr: 0.0001
    clip_grad: 10
    patience: 5
    log_steps: 50
    optimizer: 'adam'
    scheduler: 'plateau'
  wandb:
    name: 'bert' # wandb run name

lastQuery:
  seed: 42
  device: 'cpu'
  data_dir: '/opt/ml/input/data/train_dataset'
  asset_dir: 'asset/'
  file_name: 'tuning_train_data_2.csv'
  model_dir: 'models/' # model directory
  model_name: 'LastQuery.pt' # save model as model_name
  output_dir: 'output/'
  test_file_name: 'tuning_test_data.csv'  
  max_seq_len: 100
  num_workers: 1
  model_args:
    model: 'LastQuery' # model class name
    hidden_dim: 64
    n_layers: 2
    n_heads: 2
    drop_out: 0.2
  train_args:
    n_epochs: 20
    batch_size: 64
    lr: 0.0001
    clip_grad: 10
    patience: 5
    log_steps: 50
    optimizer: 'adamW'
    scheduler: 'plateau'
  wandb:
    name: 'LastQuery' # wandb run name